### ISSUE TITLE
[red]*色付き強調*みたいなのを有効にして欲しいです

### ISSUE THREAD

**Issue by Mizuho32** [titech-ssr/www.rogiken.org-root#9]
HTML見たところCSSいじるだけでいい?

**Comment by l1048576** [comment]
asciidoctor単体だと、ヘッダ部で
```css
.red {
  color: red;
}
```
的なコードが出力されるんだけど、それが入ってない(本文htmlしか生成させてないから)ので、そういうのをCSSとして入れてやればおｋです。
なんか適当な名前でscss作ってそこにまとめればいいかな？
